#!/usr/bin/env bash
set -Eeuo pipefail

NODE_DVR_URL="${NODE_DVR_URL:-${DVR_ENGINE_URL:-http://10.106.1.31:3010}}"
SITE_CONF="${SITE_CONF:-/etc/nginx/sites-available/newdomofon-video.conf}"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="${SITE_CONF}.${STAMP}.bak"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root: sudo NODE_DVR_URL=http://10.106.1.31:3010 bash scripts/apply-master-node-media-proxy.sh" >&2
  exit 1
fi

if [[ ! -f "$SITE_CONF" ]]; then
  echo "Nginx site config not found: $SITE_CONF" >&2
  exit 2
fi

NODE_DVR_URL="${NODE_DVR_URL%/}"
cp -a "$SITE_CONF" "$BACKUP"

python3 - "$SITE_CONF" "$NODE_DVR_URL" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
node_url = sys.argv[2].rstrip('/')
text = path.read_text()
start = '    # BEGIN NEWDOMOFON NODE MEDIA PROXY\n'
end = '    # END NEWDOMOFON NODE MEDIA PROXY\n'

while start in text and end in text:
    a = text.index(start)
    b = text.index(end) + len(end)
    text = text[:a] + text[b:]

block = f'''    # BEGIN NEWDOMOFON NODE MEDIA PROXY
    # Static node-direct media links generated by the master use these paths.
    # The master keeps management/UI/API, while media is served by the video node.
    location ^~ /cameras/ {{
        if ($request_method = OPTIONS) {{
            add_header Access-Control-Allow-Origin "*" always;
            add_header Access-Control-Allow-Methods "GET,HEAD,OPTIONS" always;
            add_header Access-Control-Allow-Headers "authorization,content-type,range,cache-control,pragma,accept,origin,x-requested-with" always;
            add_header Access-Control-Max-Age "600" always;
            return 204;
        }}

        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET,HEAD,OPTIONS" always;
        add_header Access-Control-Allow-Headers "authorization,content-type,range,cache-control,pragma,accept,origin,x-requested-with" always;
        add_header Access-Control-Expose-Headers "content-length,content-range,accept-ranges,cache-control,content-type" always;

        proxy_pass {node_url};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 10s;
        proxy_send_timeout 3600s;
        proxy_read_timeout 3600s;
        proxy_buffering off;
    }}

    location ^~ /files/ {{
        if ($request_method = OPTIONS) {{
            add_header Access-Control-Allow-Origin "*" always;
            add_header Access-Control-Allow-Methods "GET,HEAD,OPTIONS" always;
            add_header Access-Control-Allow-Headers "authorization,content-type,range,cache-control,pragma,accept,origin,x-requested-with" always;
            add_header Access-Control-Max-Age "600" always;
            return 204;
        }}

        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET,HEAD,OPTIONS" always;
        add_header Access-Control-Allow-Headers "authorization,content-type,range,cache-control,pragma,accept,origin,x-requested-with" always;
        add_header Access-Control-Expose-Headers "content-length,content-range,accept-ranges,cache-control,content-type" always;

        proxy_pass {node_url};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 10s;
        proxy_send_timeout 3600s;
        proxy_read_timeout 3600s;
        proxy_buffering off;
    }}

    location ^~ /device-archive/ {{
        if ($request_method = OPTIONS) {{
            add_header Access-Control-Allow-Origin "*" always;
            add_header Access-Control-Allow-Methods "GET,HEAD,OPTIONS" always;
            add_header Access-Control-Allow-Headers "authorization,content-type,range,cache-control,pragma,accept,origin,x-requested-with" always;
            add_header Access-Control-Max-Age "600" always;
            return 204;
        }}

        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET,HEAD,OPTIONS" always;
        add_header Access-Control-Allow-Headers "authorization,content-type,range,cache-control,pragma,accept,origin,x-requested-with" always;
        add_header Access-Control-Expose-Headers "content-length,content-range,accept-ranges,cache-control,content-type" always;

        proxy_pass {node_url};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 10s;
        proxy_send_timeout 3600s;
        proxy_read_timeout 3600s;
        proxy_buffering off;
    }}
    # END NEWDOMOFON NODE MEDIA PROXY

'''

marker = '    location /assets/ {'
if marker in text:
    text = text.replace(marker, block + marker, 1)
else:
    marker = '    location / {'
    if marker not in text:
        raise SystemExit('Could not find insertion point in nginx config')
    text = text.replace(marker, block + marker, 1)

path.write_text(text)
PY

nginx -t
systemctl reload nginx

echo "Applied master node media proxy"
echo "node_dvr_url=$NODE_DVR_URL"
echo "site_conf=$SITE_CONF"
echo "backup=$BACKUP"
echo
grep -nE 'BEGIN NEWDOMOFON NODE MEDIA PROXY|location \^~ /(cameras|files|device-archive)/|proxy_pass http' "$SITE_CONF" || true
