#!/usr/bin/env bash
set -Eeuo pipefail

NODE_DVR_URL="${NODE_DVR_URL:-${DVR_ENGINE_URL:-http://10.106.1.31:3010}}"
SITE_CONF="${SITE_CONF:-/etc/nginx/sites-available/newdomofon-video.conf}"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="${SITE_CONF}.${STAMP}.bak"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root: sudo NODE_DVR_URL=http://10.106.1.31:3010 bash scripts/apply-master-node-media-proxy.sh" >&2
  exit 1
fi

if [[ ! -f "$SITE_CONF" ]]; then
  echo "Nginx site config not found: $SITE_CONF" >&2
  exit 2
fi

NODE_DVR_URL="${NODE_DVR_URL%/}"
cp -a "$SITE_CONF" "$BACKUP"

python3 - "$SITE_CONF" "$NODE_DVR_URL" <<'PY'
from pathlib import Path
import re
import sys

path = Path(sys.argv[1])
node_url = sys.argv[2].rstrip('/')
text = path.read_text()

start_marker = '# BEGIN NEWDOMOFON NODE MEDIA PROXY'
end_marker = '# END NEWDOMOFON NODE MEDIA PROXY'

# Remove all previous generated blocks, even if indentation changed.
text = re.sub(
    r'\n?\s*# BEGIN NEWDOMOFON NODE MEDIA PROXY\n[\s\S]*?\n\s*# END NEWDOMOFON NODE MEDIA PROXY\n?',
    '\n',
    text,
)

# Remove orphan blocks from older broken script versions. They used a broad
# `location ^~ /cameras/` prefix, which also captured the Vue route /cameras/:id.
def remove_location_block(src: str, location_re: str) -> str:
    pattern = re.compile(location_re)
    pos = 0
    out = []
    while True:
        m = pattern.search(src, pos)
        if not m:
            out.append(src[pos:])
            break
        out.append(src[pos:m.start()])
        brace = src.find('{', m.end() - 1)
        if brace < 0:
            pos = m.end()
            continue
        depth = 0
        i = brace
        while i < len(src):
            ch = src[i]
            if ch == '{':
                depth += 1
            elif ch == '}':
                depth -= 1
                if depth == 0:
                    i += 1
                    while i < len(src) and src[i] in ' \t\r\n':
                        i += 1
                    break
            i += 1
        block = src[m.start():i]
        if 'proxy_pass http://10.106.1.31:3010' in block or 'NEWDOMOFON NODE MEDIA PROXY' in block or 'Static node-direct media links' in block:
            pos = i
        else:
            out.append(block)
            pos = i
    return ''.join(out)

for loc in [
    r'\n\s*location\s+\^~\s+/cameras/\s*\{',
    r'\n\s*location\s+\^~\s+/files/\s*\{',
    r'\n\s*location\s+\^~\s+/device-archive/\s*\{',
]:
    text = remove_location_block(text, loc)

cors = '''        if ($request_method = OPTIONS) {
            add_header Access-Control-Allow-Origin "*" always;
            add_header Access-Control-Allow-Methods "GET,HEAD,OPTIONS" always;
            add_header Access-Control-Allow-Headers "authorization,content-type,range,cache-control,pragma,accept,origin,x-requested-with" always;
            add_header Access-Control-Max-Age "600" always;
            return 204;
        }

        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET,HEAD,OPTIONS" always;
        add_header Access-Control-Allow-Headers "authorization,content-type,range,cache-control,pragma,accept,origin,x-requested-with" always;
        add_header Access-Control-Expose-Headers "content-length,content-range,accept-ranges,cache-control,content-type" always;
'''

proxy_common = f'''        proxy_pass {node_url};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 10s;
        proxy_send_timeout 3600s;
        proxy_read_timeout 3600s;
        proxy_buffering off;
'''

block = f'''    # BEGIN NEWDOMOFON NODE MEDIA PROXY
    # Static media URLs generated by the master are proxied to the video node.
    # Important: do not use `location ^~ /cameras/`, because /cameras/:id is a Vue route.
    location ~ ^/cameras/[^/]+/(?:live\\.m3u8|archive\\.m3u8|device-archive\\.m3u8|export\\.mp4|archive/ranges|device-archive/session|device-archive/ranges)$ {{
{cors}
{proxy_common}    }}

    location ^~ /files/ {{
{cors}
{proxy_common}    }}

    location ^~ /device-archive/ {{
{cors}
{proxy_common}    }}
    # END NEWDOMOFON NODE MEDIA PROXY

'''

marker = '    location /assets/ {'
if marker in text:
    text = text.replace(marker, block + marker, 1)
else:
    marker = '    location / {'
    if marker not in text:
        raise SystemExit('Could not find insertion point in nginx config')
    text = text.replace(marker, block + marker, 1)

path.write_text(text)
PY

nginx -t
systemctl reload nginx

echo "Applied master node media proxy"
echo "node_dvr_url=$NODE_DVR_URL"
echo "site_conf=$SITE_CONF"
echo "backup=$BACKUP"
echo
grep -nE 'BEGIN NEWDOMOFON NODE MEDIA PROXY|location (~|\^~) /(cameras|files|device-archive)|proxy_pass http' "$SITE_CONF" || true
