#!/usr/bin/env bash
set -Eeuo pipefail

ENV_FILE="${NEWDOMOFON_ENV_FILE:-/etc/newdomofon-video/app.env}"
PROJECT_DIR="${PROJECT_DIR:-/opt/newdomofon-video-node}"
STATE_DIR="${DVR_RUNTIME_STORAGE_STATE_DIR:-/var/lib/newdomofon-video}"

[[ "$(id -u)" -eq 0 ]] || {
  echo "prepare-node-runtime-storage: run as root" >&2
  exit 77
}

if [[ -r "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
fi

RUNTIME_USER="${DVR_RUNTIME_USER:-newdomofon}"
RUNTIME_GROUP="${DVR_RUNTIME_GROUP:-newdomofon}"
if ! id "$RUNTIME_USER" >/dev/null 2>&1; then
  RUNTIME_USER=root
  RUNTIME_GROUP=root
elif ! getent group "$RUNTIME_GROUP" >/dev/null 2>&1; then
  RUNTIME_GROUP="$(id -gn "$RUNTIME_USER")"
fi

DVR_ROOT_VALUE="${DVR_ROOT:-/var/lib/newdomofon-video/dvr}"
DVR_STORAGE_ROOTS_VALUE="${DVR_STORAGE_ROOTS:-$DVR_ROOT_VALUE}"
REQUIRE_MOUNTPOINT="${DVR_DISK_REQUIRE_MOUNTPOINT:-false}"
EVENT_DB="${DVR_EVENT_DB:-/var/lib/newdomofon-video/events/events.sqlite3}"
EVENT_ROOT="$(dirname "$EVENT_DB")"

mapfile -t STORAGE_ROOTS < <(
  python3 - "$DVR_STORAGE_ROOTS_VALUE" "$DVR_ROOT_VALUE" <<'PY'
import os
import sys
raw = sys.argv[1].strip() or sys.argv[2]
seen = set()
for item in raw.split(','):
    item = item.strip()
    if not item:
        continue
    value = os.path.abspath(item)
    if value not in seen:
        seen.add(value)
        print(value)
PY
)

((${#STORAGE_ROOTS[@]} > 0)) || {
  echo "prepare-node-runtime-storage: no storage roots configured" >&2
  exit 64
}

case "${REQUIRE_MOUNTPOINT,,}" in
  1|true|yes|on) REQUIRE_MOUNTPOINT=true ;;
  *) REQUIRE_MOUNTPOINT=false ;;
esac

install -d -m 0755 "$STATE_DIR"
SIGNATURE="$(printf '%s\0' "$RUNTIME_USER" "$RUNTIME_GROUP" "$EVENT_ROOT" "${STORAGE_ROOTS[@]}" | sha256sum | awk '{print $1}')"
MARKER="$STATE_DIR/.runtime-storage-prepared-$SIGNATURE"
[[ -f "$MARKER" ]] && exit 0

install -d -o "$RUNTIME_USER" -g "$RUNTIME_GROUP" -m 0750 "$EVENT_ROOT"
chown -R "$RUNTIME_USER:$RUNTIME_GROUP" "$EVENT_ROOT"
find "$EVENT_ROOT" -xdev -type d -exec chmod u+rwx {} +
find "$EVENT_ROOT" -xdev -type f -exec chmod u+rw {} +

ready=true
for root in "${STORAGE_ROOTS[@]}"; do
  case "$root" in
    /|/bin|/boot|/dev|/etc|/home|/opt|/proc|/root|/run|/sys|/usr|/var)
      echo "prepare-node-runtime-storage: refusing unsafe storage root: $root" >&2
      exit 64
      ;;
  esac

  if [[ "$REQUIRE_MOUNTPOINT" == true ]] && ! mountpoint -q "$root"; then
    echo "prepare-node-runtime-storage: waiting for configured mountpoint: $root" >&2
    ready=false
    continue
  fi

  if [[ ! -d "$root" ]]; then
    if [[ "$REQUIRE_MOUNTPOINT" == true ]]; then
      ready=false
      continue
    fi
    install -d -o "$RUNTIME_USER" -g "$RUNTIME_GROUP" -m 0750 "$root"
  fi

  mount_options="$(findmnt -no OPTIONS --target "$root" 2>/dev/null || true)"
  if [[ ",$mount_options," == *,ro,* ]]; then
    echo "prepare-node-runtime-storage: filesystem is read-only: $root" >&2
    ready=false
    continue
  fi

  # Old nodes often recorded as root. The current service uses newdomofon.
  # Directory ownership is sufficient for creating/removing archive segments;
  # only mutable live playlists/files also need their file ownership migrated.
  find "$root" -xdev -type d -exec chown "$RUNTIME_USER:$RUNTIME_GROUP" {} +
  find "$root" -xdev -type d -exec chmod u+rwx {} +
  find "$root" -xdev -type f \( -path '*/live/*' -o -name '*.m3u8' \) \
    -exec chown "$RUNTIME_USER:$RUNTIME_GROUP" {} +
  find "$root" -xdev -type f \( -path '*/live/*' -o -name '*.m3u8' \) \
    -exec chmod u+rw {} +
done

# During a normal archive update /etc is writable and the explicit drop-in is
# installed. During the recurring sandboxed disk-guard run /etc is read-only;
# permissions can still be repaired without making the oneshot fail.
if [[ -w /etc/systemd/system ]]; then
  DROPIN_DIR=/etc/systemd/system/newdomofon-video-dvr.service.d
  DROPIN_FILE="$DROPIN_DIR/20-storage-roots.conf"
  install -d -m 0755 "$DROPIN_DIR"
  python3 - "$DROPIN_FILE" "${STORAGE_ROOTS[@]}" <<'PY'
from pathlib import Path
import sys

def quote(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'

path = Path(sys.argv[1])
roots = sys.argv[2:]
lines = [
    '# Generated by prepare-node-runtime-storage.sh',
    '[Service]',
]
for root in roots:
    lines.append(f'ReadWritePaths={quote(root)}')
path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
PY
  chmod 0644 "$DROPIN_FILE"
  systemctl daemon-reload
fi

if [[ "$ready" == true ]]; then
  printf 'runtime_user=%s\nruntime_group=%s\nevent_root=%s\nstorage_roots=%s\nprepared_at=%s\n' \
    "$RUNTIME_USER" "$RUNTIME_GROUP" "$EVENT_ROOT" "${STORAGE_ROOTS[*]}" "$(date --iso-8601=seconds)" \
    >"$MARKER"
  chmod 0600 "$MARKER"
  echo "Node runtime storage prepared for $RUNTIME_USER:$RUNTIME_GROUP"
else
  echo "prepare-node-runtime-storage: storage preparation is incomplete" >&2
fi
